-- Tabla de empleados
CREATE TABLE empleados (
    id_empleado      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR2(100) NOT NULL,
    apellido         VARCHAR2(100) NOT NULL,
    fecha_ingreso    DATE NOT NULL,
    activo           CHAR(1) DEFAULT 'S' CHECK (activo IN ('S', 'N'))
);

-- Tabla de ausencias
CREATE TABLE ausencias (
    id_ausencia      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_empleado      NUMBER NOT NULL,
    fecha_ausencia   DATE NOT NULL,
    dias_ausencia    NUMBER(3) DEFAULT 1 CHECK (dias_ausencia >= 1),
    tipo             VARCHAR2(20) CHECK (tipo IN ('Justificada', 'Injustificada')),
    motivo           VARCHAR2(200),
    fecha_registro   DATE DEFAULT SYSDATE,
    
    CONSTRAINT fk_empleado FOREIGN KEY (id_empleado)
        REFERENCES empleados(id_empleado)
        ON DELETE CASCADE
);



