CREATE TABLE auditoria_ausencias (
    id_auditoria        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_empleado         NUMBER NOT NULL,
    fecha_ausencia      DATE NOT NULL,
    motivo              VARCHAR2(100),
    usuario_creador     VARCHAR2(30),
    fecha_registro      DATE DEFAULT SYSDATE
);
